### ISSUE TITLE
please help me about the problem - adaptive learning rate in tracking.

### ISSUE THREAD

**Issue by MinboWang** [martin-danelljan/Continuous-ConvOp#1]
hello, martin,
sorry to disturb you. 
Rencenty,  I have been doing some work about occlusion and abrupt changes in tracking. I have tested your tracker - C-COT, it works really well. The output is very stable although it doesn't do any thing about tracking - quality - detecting & feedback.  
I have also read your paper about tracker - SRDCFdecon, which has done many things about learning rate.  The way to set adaptive learning rate has bothered me for a long time, and I have attemped to use PSR  and max response <reference LCT : Long-term Correlation Tracking>. However, it is hard to set a unified threshod which determines tracking state for the whole tracking process. Especially, both of them can't distinguish quick deformation and occlusion. I also attempted to do some improvements based on them, but the result is not so good. I think maybe your tracker - SRDCFdecon can give me some good inspires, and I have visited your homepage about SRDCFdecon. Althogh it says the code will be coming so, I can't wait seeing the wonderful implementation and result.  So, I wanna know if it is convenient to share your code with SRDCFdecon.
It will be my plesure to get your reply, thank you !

**Comment by martin-danelljan** [comment]
There is a Matlab implementation of SRDCFdecon available at [the project webpage](http://www.cvl.isy.liu.se/research/objrec/visualtracking/decontrack/index.html).
