### ISSUE TITLE
About the VOT_integration

### ISSUE THREAD

**Issue by Evelyn5589** [martin-danelljan/Continuous-ConvOp#2]
Hello,I copy this template configuration file to my VOT workspace.Then ,it shows that error using system_wrapper>run_once (line 229).It doesn't work,I have tried many times.

**Comment by martin-danelljan** [comment]
You have to provide me with information about the error. Have you set the path to the C-COT repository in the configuration file?

**Comment by Evelyn5589** [comment]
Yes ,I have set the path.Sorry ,I can't find images.txt  ,as it's in "  fid = fopen('images.txt','r');  ".
  Do I need to run the whole VOT2016  in  the C-COT repository?

**Comment by martin-danelljan** [comment]
You need to run the VOT toolkit of course. Im not sure what you mean with "in the C-COT repository". It should work if you run the VOT toolkit normally. You dont have to put it inside the C-COT repository. Have you been able to run any other tracker in the VOT repo?

**Comment by Evelyn5589** [comment]
Yes.I can run the NCC tracker in the  VOT repo successfully. 
The  "fopen('images.txt','r');"  in  benchmark_wrapper/vot_initialize.m may not work. 
Thanks,I'll try tomorrow.

**Comment by Evelyn5589** [comment]
Hello,martin,sorry to disturb you again.I print many variables in benchmark_wrapper/benchmark_tracker_wrapper.m  .  And it catches error when the code below is  executed:
%convert the results to rectangle format
otb_res = convert_to_rect(otb_res);

So,the function convert_to_rect() may not be found.How should I solve it ?

**Comment by martin-danelljan** [comment]
I have updated the benchmark_wrapper/benchmark_tracker_wrapper.m file now. Please notify me if it works or not.

**Comment by Evelyn5589** [comment]
Yeah !   It works in the the VOT repo . Thank you so much !

**Comment by martin-danelljan** [comment]
Thank you for reporting the issue.

**Comment by Evelyn5589** [comment]
Hello,martin,I have run CCOT in the VOT2016 repo for 3 days.

And  the expected overlap scores for baseline is 0.3241.
But in http://www.cvl.isy.liu.se/research/objrec/visualtracking/conttrack/C-COT_ECCV16_poster.pdf ,it shows that the EAO is 0.331.

Is EAO and 'the expected overlap scores for baseline' the same  parameter ?

**Comment by Evelyn5589** [comment]
[report_vot2016_CCOT.zip](https://github.com/martin-danelljan/Continuous-ConvOp/files/734425/report_vot2016_CCOT.zip)

Hello,this is the VOT2016 article report .I choose SSKCF to compare with CCOT.(Because VOT cose requests there should be more than 1 tracker).

**Comment by martin-danelljan** [comment]
As stated in the readme file, small variations in the results can occur due to e.g.
- Some updates in the code that I did prior to the release
- The vgg network that we use seems to be constantly updated on the matconvnet site
- Versions of the vot-toolkit, matconvnet etc.

Some local parameter search usually brings the result over 0.33 again. The result I get on my machine with the current version is 0.3388. If you send me the number of bytes of you network file, I can check if I have the same.

**Comment by Evelyn5589** [comment]
The network file I use is imagenet-vgg-m-2048.mat.And  the number of bytes of the file is 330M.
