### ISSUE TITLE
Mix training and test code?

### ISSUE THREAD

**Issue by RogerChern** [martin-danelljan/Continuous-ConvOp#3]
After digged into the `tracker.m` file in the implementation directory, I found the code a little bit confusing.

According to the ECCV16 paper, the training is done iteratively with CG method and groundtruth. And test is done with gird search and newton method.

But in the `tracker.m` file, training code is not commented out if the intention is to do test (and the filter is not trained at all). And if the intention is to do training, the groundtruth is not used.

So I wonder if I misunderstood the paper or I just need to tailor the code if I want to use it.

**Comment by ujsyehao** [comment]
@RogerChern Hi, I have a problem, when I type the command  sudo git submodule update.
It has the error
`Cloning into 'external_libs/matconvnet'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:vlfeat/matconvnet.git' into submodule path 'external_libs/matconvnet' failed
`
Can you help me solve the problem?

**Comment by chenxinhua** [comment]
which platform does this code need. including linux, matlab version.

**Comment by martin-danelljan** [comment]
@RogerChern I have added some section comments in tracker.m to clarify this. But note that the training is not done with the ground truth, the model is trained online while it is tracking.

@chenxinhua I have tested the code on linux (Ubuntu 14.04) and Windows. It should work on both.

**Comment by chenxinhua** [comment]
thank you very much,your code is so wonderful,I deploy it successfully on  centos7,matlab2014a.

**Comment by RogerChern** [comment]
@martin-danelljan 
Although I already figured it out, still you have my sincere thanks.
