### ISSUE TITLE
git submodule update have problems

### ISSUE THREAD

**Issue by ujsyehao** [martin-danelljan/Continuous-ConvOp#4]
when I type the command 'git submodule update'
It has the error:
Cloning into 'external_libs/matconvnet'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by martin-danelljan** [comment]
Have you added your ssh key on Github?
[https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)
