### ISSUE TITLE
The compressed_dim parameter for cnn features

### ISSUE THREAD

**Issue by egundogdu** [martin-danelljan/Continuous-ConvOp#5]
Hi Martin,
In the VOT2016_settings of CCOT, the following line exists.
    cnn_params.compressed_dim = [16 64];    
Nevertheless, I could not find its usage to compressed the feature maps to the values in the RHS of the above command.
Could you please clarify this point ?

**Comment by martin-danelljan** [comment]
Hi.
Thank you for your comment. Those parameters are not used in C-COT and were accidentally included while copy-pasting code. They are used in our new [ECO tracker](https://github.com/martin-danelljan/ECO) though to set the dimensionality of the compressed features.
