### ISSUE TITLE
How to integrate the c-cot tracker inot the vot-toolkit

### ISSUE THREAD

**Issue by Wanggcong** [martin-danelljan/Continuous-ConvOp#7]
I followed the instructions http://www.votchallenge.net/howto/workspace.html :
(1) Run toolkit_path.
(2) Go to vot-workspace directory. Run matlab and execute workspace_create command.
(3) Select an experiment stack that you want to use. (have prepared sequence)
(4) Enter the unique indentifier of your tracker, e.g. ccot
(5) Select the interpreter used in your tracker, e.g. matlab.
(6) edit the tracker_xxx.m, e.g. tracker_ccot.m

CCOT_repo_path = '/home/wang/projects/vot2017/C-COT/Continuous-ConvOp-master';

tracker_label = 'CCOT';
tracker_command = generate_matlab_command('benchmark_tracker_wrapper(''CCOT'', ''VOT2016_settings'', true)', {[CCOT_repo_path '/VOT_integration/benchmark_wrapper']});
tracker_interpreter = 'matlab';
tracker_trax = false;

(7) I also successfully reproduced your c-cot tracker in another folder, e.g. /home/wang/projects/vot2017/C-COT/Continuous-ConvOp-master

(8)run the script: run_test.m, choose the action 'b', sequence '1', I got some errors:

Error using system_wrapper>run_once (line 229)
No result produced by tracker. Report written to "/home/wang/projects/vot2017/vot-toolkit-master/workspace/logs/ccot/20170511T090124"

Error in system_wrapper (line 39)
[Tr, Tm] = run_once(context.directory, tracker, sequence, start, context);

Error in workspace_test (line 90)
[trajectory, time] = tracker.run(tracker, sequences{current_sequence}, struct('repetition', 1, 'repetitions', 1));

Error in run_test (line 10)
workspace_test(tracker, sequences);

What's wrong with my integration? Thank you!

**Comment by akeba1** [comment]
Check the logfile, and also look in C-COT/Continuous-ConvOp-master/VOT_integration/error_reports for a .mat file containing the output error inside the toolkit. They've also released code for an improved tracker that has GPU support enabled at [https://github.com/martin-danelljan/ECO](https://github.com/martin-danelljan/ECO).

**Comment by martin-danelljan** [comment]
As @akeba1 mentioned. Check the load the error report and display it with the getReport function in Matlab.

The code has been tested to work with the following version of the VOT toolkit:
[64da0655cf973ef4a32923c72d5c423f908325a5](https://github.com/votchallenge/vot-toolkit/tree/64da0655cf973ef4a32923c72d5c423f908325a5)

We are still working on the full GPU support for ECO.

**Comment by martin-danelljan** [comment]
The ECO tracker now includes VOT2017 integration. 
We have also added full GPU support.
